services:
  - type: web
    name: ppl2026
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type"
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /firebase-messaging-sw.js
        name: Cache-Control
        value: no-cache
      - path: /firebase-messaging-sw.js
        name: Service-Worker-Allowed
        value: /
      - path: /manifest.json
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /firebase-messaging-sw.js
        destination: /firebase-messaging-sw.js
      - type: rewrite
        source: /*
        destination: /index.html
